version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mySqlCont
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: david
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: my_store
    volumes:
      - ./my-db:/var/lib/mysql
    ports:
      - '3306:3306'
